apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tenant }}-app
  namespace: {{ tenant }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ tenant }}-app
  template:
    metadata:
      labels:
        app: {{ tenant }}-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
