apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${tenant}-ingress
  namespace: ${tenant}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ${tenant}.13.229.151.83.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${tenant}-svc
            port:
              number: 80
